package com.quickbite.config;

import com.quickbite.model.*;
import com.quickbite.repository.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import java.util.ArrayList;
import java.util.List;

@Component
public class DataLoader implements CommandLineRunner {

    private final RestaurantRepository restaurantRepo;
    private final DeliveryPartnerRepository partnerRepo;

    public DataLoader(RestaurantRepository restaurantRepo, DeliveryPartnerRepository partnerRepo) {
        this.restaurantRepo = restaurantRepo;
        this.partnerRepo = partnerRepo;
    }

    @Override
    public void run(String... args) {
        if (restaurantRepo.count() > 0) return;
        System.out.println("[QuickBite] Seeding database...");
        seedPartners();
        seedRestaurants();
        System.out.println("[QuickBite] Seeded " + restaurantRepo.count() + " restaurants, " + partnerRepo.count() + " partners.");
    }

    private void seedPartners() {
        List<DeliveryPartner> list = new ArrayList<>();
        list.add(dp("Kunal Patil","9889213677","Bike","MH12GH5252","Camp","Central",4.3,3.1,"KP"));
        list.add(dp("Aditya More","9829004945","Scooter","MH12CD5331","Yerwada","East",3.9,2.4,"AM"));
        list.add(dp("Vishal Patil","9896664657","Scooter","MH12GH2608","Shivajinagar","Central",4.3,5.2,"VP"));
        list.add(dp("Abhishek Kale","9877578122","Bike","MH12AB7786","Wakad","West",4.3,4.1,"AK"));
        list.add(dp("Swapnil Joshi","9896024554","Bike","MH12EF2372","Kharadi","East",4.9,6.8,"SJ"));
        list.add(dp("Tejas Patil","9875721788","Scooter","MH12GH3423","Hadapsar","East",4.4,6.9,"TP"));
        list.add(dp("Pratik Deshmukh","9851743811","Bike","MH12CD6644","Kharadi","East",4.4,3.3,"PD"));
        list.add(dp("Kunal More","9870755604","Bike","MH12CD1647","Kalyani Nagar","East",4.0,7.5,"KM"));
        list.add(dp("Rohit Shinde","9823456712","Bike","MH12BC9910","Baner","West",4.2,2.8,"RS"));
        list.add(dp("Nikhil Jadhav","9834561234","Scooter","MH12FG4421","Koregaon Park","Central",4.6,4.0,"NJ"));
        partnerRepo.saveAll(list);
    }

    private void seedRestaurants() {
        saveRestaurant("Le Plaisir","Deccan Gymkhana","Cafe, Italian, Continental, Salad, Sandwich, Pizza, Beverage","Survey 759/125, Prabhat Road, Rajkamal, Opposite Kelkar Eye Hospital, Deccan Gymkhana, Pune","🍕",
            4.9,4840,200,"₹₹",18.514254,73.838658,"Expresso Panacota, Banana Nutella Crepe, New York Baked Cheesecake, Lamb Bolognese",22,            List.of(new String[]{"Expresso Panacota","Chef's special — a crowd favourite","50"}, new String[]{"Banana Nutella Crepe","Made fresh daily with hand-picked ingredients","60"}, new String[]{"New York Baked Cheesecake","A timeless classic, done the right way","80"}, new String[]{"Lamb Bolognese","Bursting with authentic flavour","100"}, new String[]{"Hazelnut Cheese Cake","Customer's most loved dish","60"}, new String[]{"Caffe Frappe","House specialty — highly recommended","70"}));
        saveRestaurant("AB's - Absolute Barbecues","Wakad Road","North Indian, BBQ, Fast Food, Desserts","Second Floor, White Square Building, Wakad Road, Hinjewadi Pune","🍔",
            4.7,8330,200,"₹₹",18.591322,73.753196,"Kashmiri Phirni, Beetroot Soup, Orange Pastry, Chicken Mix Grill",50,            List.of(new String[]{"Kashmiri Phirni","Chef's special — a crowd favourite","50"}, new String[]{"Beetroot Soup","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Orange Pastry","A timeless classic, done the right way","80"}, new String[]{"Chicken Mix Grill","Bursting with authentic flavour","100"}, new String[]{"Rabbit","Customer's most loved dish","60"}, new String[]{"Paan Icecream","House specialty — highly recommended","70"}));
        saveRestaurant("Malaka Spice","Koregaon Park","Thai, Japanese, Asian","Opposite Oxford Properties, Lane 5, North Main Road, Koregaon Park, Pune","🥡",
            4.7,4881,200,"₹₹",18.537548,73.897462,"Chicken Frittura, Roti Jhala, Jaggery Ice Cream, Chicken Murtabak",33,            List.of(new String[]{"Chicken Frittura","Chef's special — a crowd favourite","50"}, new String[]{"Roti Jhala","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Jaggery Ice Cream","A timeless classic, done the right way","80"}, new String[]{"Chicken Murtabak","Bursting with authentic flavour","100"}, new String[]{"Penang Curry","Customer's most loved dish","60"}, new String[]{"Thai Ice Tea","House specialty — highly recommended","70"}));
        saveRestaurant("Barbeque Nation","JM Road","BBQ, Mughlai, Kebab, North Indian, Desserts","3rd Floor, R Deccan Mall, JM Road, Pune","🍚",
            4.7,4503,200,"₹₹",18.516357,73.842372,"Shrimp Soup, Honey Mustard Chicken, Cajun Spice Potato, Pan Kulfi",20,            List.of(new String[]{"Shrimp Soup","Chef's special — a crowd favourite","50"}, new String[]{"Honey Mustard Chicken","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Cajun Spice Potato","A timeless classic, done the right way","80"}, new String[]{"Pan Kulfi","Bursting with authentic flavour","100"}, new String[]{"Grilled Prawns","Customer's most loved dish","60"}, new String[]{"Barbeque","House specialty — highly recommended","70"}));
        saveRestaurant("Effingut","Koregaon Park","North Indian, Continental, Oriental, Finger Food, Fast Food,","Plot 389, Lane 6, Koregaon Park, Pune","🍔",
            4.7,3805,200,"₹₹",18.533958,73.898583,"Apple Sider, Peach Beer, Roasted Chilli Chicken, Chicken Schnitzel",33,            List.of(new String[]{"Apple Sider","Chef's special — a crowd favourite","50"}, new String[]{"Peach Beer","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Roasted Chilli Chicken","A timeless classic, done the right way","80"}, new String[]{"Chicken Schnitzel","Bursting with authentic flavour","100"}, new String[]{"Craft Beer","Customer's most loved dish","60"}, new String[]{"Brewed Beer","House specialty — highly recommended","70"}));
        saveRestaurant("Kayani Bakery","East Street","Bakery","6, DEH, Koyani Road, Camp, East Street, Pune","🎂",
            4.5,13088,50,"₹",18.514863,73.879831,"Shrewsberry Cookie, Coconut Biscuits, Mawa Cup Cake, Mava Cakes",28,            List.of(new String[]{"Shrewsberry Cookie","Chef's special — a crowd favourite","50"}, new String[]{"Coconut Biscuits","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Mawa Cup Cake","A timeless classic, done the right way","80"}, new String[]{"Mava Cakes","Bursting with authentic flavour","100"}, new String[]{"Vanilla Muffin","Customer's most loved dish","60"}, new String[]{"Vanilla Sponge Cake","House specialty — highly recommended","70"}));
        saveRestaurant("Darshan","Baner","Continental, Chinese, Mexican, Fast Food, Street Food, Desse","Amar Business Park, Baner, Pune","🍔",
            4.5,7846,800,"₹₹₹",18.568697,73.766969,"Papdi Chaat Nacho, Soya Keema Pav, Chiku Shake, Cream Mango",48,            List.of(new String[]{"Papdi Chaat Nacho","Chef's special — a crowd favourite","190"}, new String[]{"Soya Keema Pav","Made fresh daily with hand-picked ingredients","260"}, new String[]{"Chiku Shake","A timeless classic, done the right way","320"}, new String[]{"Cream Mango","Bursting with authentic flavour","380"}, new String[]{"Shyam Savera","Customer's most loved dish","220"}, new String[]{"Sizzling Vegetables","House specialty — highly recommended","290"}));
        saveRestaurant("Vaishali","FC Road","South Indian, Street Food, Fast Food, Beverages, Desserts","1218/1, Rage Path, Ganeshwadi, Shivajinagar, FC Road, Pune","🍔",
            4.5,5748,500,"₹₹₹",18.520834,73.841314,"South Indian Platter, Maysore Masala Dosa, Kokum Sharbat, Idli Vada Sambar",19,            List.of(new String[]{"South Indian Platter","Chef's special — a crowd favourite","120"}, new String[]{"Maysore Masala Dosa","Made fresh daily with hand-picked ingredients","160"}, new String[]{"Kokum Sharbat","A timeless classic, done the right way","200"}, new String[]{"Idli Vada Sambar","Bursting with authentic flavour","240"}, new String[]{"Coconut Chatni","Customer's most loved dish","140"}, new String[]{"Onion Uthappa","House specialty — highly recommended","180"}));
        saveRestaurant("Pop Tate's","Viman Nagar","Bar Food, Continental, Chinese, North Indian, Desserts, Beve","Shop T08, 3rd Floor, Phoenix Market City Mall, Viman Nagar, Pune","🎂",
            4.8,2706,200,"₹₹",18.562562,73.917012,"Fruit Passion Mocktail, Passion Ice Tea, Pepper Wine Chicken, Thai Paneer",43,            List.of(new String[]{"Fruit Passion Mocktail","Chef's special — a crowd favourite","50"}, new String[]{"Passion Ice Tea","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Pepper Wine Chicken","A timeless classic, done the right way","80"}, new String[]{"Thai Paneer","Bursting with authentic flavour","100"}, new String[]{"Chicken Pops","Customer's most loved dish","60"}, new String[]{"Sizzler Classic","House specialty — highly recommended","70"}));
        saveRestaurant("Gong","Baner","Chinese, Sushi, Asian, Japanese, Beverages, Thai","Unit 22 & 23, Survey 20 & 21, Ground Floor, Balewadi High Street, Near Balewadi, Tal, Baner, Pune","🥡",
            4.9,1831,200,"₹₹",18.570418,73.774204,"Chicken Minestrone Soup, Crab Ravioli, Ebi Tempura Roll, Prawn Dim Sums",46,            List.of(new String[]{"Chicken Minestrone Soup","Chef's special — a crowd favourite","50"}, new String[]{"Crab Ravioli","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Ebi Tempura Roll","A timeless classic, done the right way","80"}, new String[]{"Prawn Dim Sums","Bursting with authentic flavour","100"}, new String[]{"Chocolate Dome","Customer's most loved dish","60"}, new String[]{"Asparagus Tempura","House specialty — highly recommended","70"}));
        saveRestaurant("The Urban Foundry","Balewadi","Bar Food, North Indian, Chinese, Fast Food, Desserts, Bevera","Shop 1, High Street, Cummins India Office Campus, Link Road, Balewadi, Pune","🍔",
            4.6,3974,200,"₹₹",18.569373,73.77479,"Bacon Naan, Potato Popcorn, Red Velvet Kulfi Duet, Thai Chicken Thigh",45,            List.of(new String[]{"Bacon Naan","Chef's special — a crowd favourite","50"}, new String[]{"Potato Popcorn","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Red Velvet Kulfi Duet","A timeless classic, done the right way","80"}, new String[]{"Thai Chicken Thigh","Bursting with authentic flavour","100"}, new String[]{"Butter Chicken Kulcha","Customer's most loved dish","60"}, new String[]{"Chettinad Pizza","House specialty — highly recommended","70"}));
        saveRestaurant("The French Window Patisserie","Koregaon Park","Cafe, Desserts, French, Bakery, European, Shake","Ganga Fortune Society, Lane 5, Meera Nagar, Koregaon Park, Pune","🎂",
            4.9,1671,600,"₹₹₹",18.537432,73.897714,"Trois Chocolat, Chocolate Flan, Mille Feuille, Choco Coffee",33,            List.of(new String[]{"Trois Chocolat","Chef's special — a crowd favourite","140"}, new String[]{"Chocolate Flan","Made fresh daily with hand-picked ingredients","190"}, new String[]{"Mille Feuille","A timeless classic, done the right way","240"}, new String[]{"Choco Coffee","Bursting with authentic flavour","290"}, new String[]{"Lemon Mousse","Customer's most loved dish","170"}, new String[]{"Avocado Toast","House specialty — highly recommended","220"}));
        saveRestaurant("Santè Spa Cuisine","Koregaon Park","Continental, Healthy Food, Mediterranean, Shake","Lane 1, Near Sunderban Resorts, Koregaon Park, Pune","🍦",
            4.9,1511,200,"₹₹",18.537416,73.88889,"Bajra Risotto, Spinach Hummus, Whole Wheat Spaghetti, Healthy Veg Food",30,            List.of(new String[]{"Bajra Risotto","Chef's special — a crowd favourite","50"}, new String[]{"Spinach Hummus","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Whole Wheat Spaghetti","A timeless classic, done the right way","80"}, new String[]{"Healthy Veg Food","Bursting with authentic flavour","100"}, new String[]{"Beetroot Hummus","Customer's most loved dish","60"}, new String[]{"Strawberry Lemonade","House specialty — highly recommended","70"}));
        saveRestaurant("Savya Rasa","Koregaon Park","South Indian, Mangalorean, Kerala, Chettinad, Beverages","Flat 2, Survey 479 & 480, Gera Serenity, North Main Road, Koregaon Park, Pune","🥞",
            4.9,1309,200,"₹₹",18.538862,73.886621,"Bun Paratha, Pallipalayam Kozhi, Palm Sugar, Vegetable Stew",29,            List.of(new String[]{"Bun Paratha","Chef's special — a crowd favourite","50"}, new String[]{"Pallipalayam Kozhi","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Palm Sugar","A timeless classic, done the right way","80"}, new String[]{"Vegetable Stew","Bursting with authentic flavour","100"}, new String[]{"Neer Dosa","Customer's most loved dish","60"}, new String[]{"Filtered Coffee","House specialty — highly recommended","70"}));
        saveRestaurant("Theobroma","Kothrud","Bakery, Desserts, Beverages, Fast Food","Shop 16, Fountain Head Apartment, Karishma Society, Kothrud, Pune","🍔",
            4.4,5826,150,"₹",18.502072,73.821882,"Dutch Truffle Cake, Red Velvet, Pastries, Cake",29,            List.of(new String[]{"Dutch Truffle Cake","Chef's special — a crowd favourite","50"}, new String[]{"Red Velvet","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Pastries","A timeless classic, done the right way","80"}, new String[]{"Cake","Bursting with authentic flavour","100"}));
        saveRestaurant("Ovenstory Pizza","Baner","Pizza","Survey 182, House 2, Near Baner Nagri Bank, Baner, Pune","🍕",
            4.4,6693,250,"₹₹",18.559803,73.789653,"Paneer Picante Pizza, Piping Hot Pizza, Mutton Pizza, Molten Lava Cake",39,            List.of(new String[]{"Paneer Picante Pizza","Chef's special — a crowd favourite","60"}, new String[]{"Piping Hot Pizza","Made fresh daily with hand-picked ingredients","80"}, new String[]{"Mutton Pizza","A timeless classic, done the right way","100"}, new String[]{"Molten Lava Cake","Bursting with authentic flavour","120"}, new String[]{"Pizzas","Customer's most loved dish","70"}, new String[]{"Sauce","House specialty — highly recommended","90"}));
        saveRestaurant("Cafe Goodluck","Deccan Gymkhana","North Indian, Mughlai, Maharashtrian, Biryani, Desserts","759/75, Goodluck Chowk, Deccan Gymkhana, Pune","🍚",
            4.4,6265,800,"₹₹₹",18.517429,73.841528,"Tawa Chicken Boneless, Bun Butter Omelette, Bun Maska Pav, Rumaali Roti",20,            List.of(new String[]{"Tawa Chicken Boneless","Chef's special — a crowd favourite","190"}, new String[]{"Bun Butter Omelette","Made fresh daily with hand-picked ingredients","260"}, new String[]{"Bun Maska Pav","A timeless classic, done the right way","320"}, new String[]{"Rumaali Roti","Bursting with authentic flavour","380"}, new String[]{"Bun Omlet","Customer's most loved dish","220"}, new String[]{"Omelette Pav","House specialty — highly recommended","290"}));
        saveRestaurant("Barbeque Nation - Sayaji Hotel","Wakad","BBQ, Mughlai, Kebab, North Indian, Desserts","135/136, 10th Floor, Mumbai-Bangalore Bypass Highway, Wakad, Pune","🍚",
            4.5,3757,200,"₹₹",18.599506,73.754717,"Grilled Shrimp, Chocolate Chip Brownie, Cajun Potato, Pan Kulfi",50,            List.of(new String[]{"Grilled Shrimp","Chef's special — a crowd favourite","50"}, new String[]{"Chocolate Chip Brownie","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Cajun Potato","A timeless classic, done the right way","80"}, new String[]{"Pan Kulfi","Bursting with authentic flavour","100"}, new String[]{"Grilled Pineapple","Customer's most loved dish","60"}, new String[]{"Fried Corn","House specialty — highly recommended","70"}));
        saveRestaurant("The J","Viman Nagar","Fast Food, Beverages, Shake","Shop 4, Clover Chest Society, Dutta Mandir Road, Near Corporation Bank, Viman Nagar, Pune","🍔",
            4.3,5210,600,"₹₹₹",18.565201,73.911391,"Chicken Sausage Fries, Chilli Cheese Fries, Loaded Fries, Milkshakes",42,            List.of(new String[]{"Chicken Sausage Fries","Chef's special — a crowd favourite","140"}, new String[]{"Chilli Cheese Fries","Made fresh daily with hand-picked ingredients","190"}, new String[]{"Loaded Fries","A timeless classic, done the right way","240"}, new String[]{"Milkshakes","Bursting with authentic flavour","290"}, new String[]{"Oreo Shake","Customer's most loved dish","170"}));
        saveRestaurant("Viman Nagar Social","Viman Nagar","North Indian, Chinese, Burger, Rolls, Pizza, Momos, Continen","T 02 & 03, 3rd Floor, Phoenix Market City, Viman Nagar Road, Viman Nagar, Pune","🍕",
            4.5,3132,200,"₹₹",18.562572,73.917064,"School Chicken Tikka, Multani Mushroom, Goan Prawn Curry, Murgh Ghee Roast",43,            List.of(new String[]{"School Chicken Tikka","Chef's special — a crowd favourite","50"}, new String[]{"Multani Mushroom","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Goan Prawn Curry","A timeless classic, done the right way","80"}, new String[]{"Murgh Ghee Roast","Bursting with authentic flavour","100"}, new String[]{"Achari Paneer","Customer's most loved dish","60"}, new String[]{"Kadhi Chawal","House specialty — highly recommended","70"}));
        saveRestaurant("Andaground","Aundh","Fast Food, Street Food, North Indian, Beverages, Shake","Shop A 1, Sai Heritage, Near Medipoint Hospital, Aundh, Pune","🍔",
            4.8,799,600,"₹₹₹",18.565334,73.8006,"Keema Ghotala, Australian Fry, Chicken Omelette, Masala Maggi",36,            List.of(new String[]{"Keema Ghotala","Chef's special — a crowd favourite","140"}, new String[]{"Australian Fry","Made fresh daily with hand-picked ingredients","190"}, new String[]{"Chicken Omelette","A timeless classic, done the right way","240"}, new String[]{"Masala Maggi","Bursting with authentic flavour","290"}, new String[]{"Sunny Side","Customer's most loved dish","170"}, new String[]{"Chicken Kheema","House specialty — highly recommended","220"}));
        saveRestaurant("Cafe Goa","Viman Nagar","Goan, Seafood","Shop 3-4, Faith Center, Sakore Nagar, Near NEXA Showroom, Viman Nagar, Pune","🐟",
            4.8,715,200,"₹₹",18.561607,73.90723,"Rus Omelette, Chicken Caffreal, Squid Masala, Authentic Goan Food",40,            List.of(new String[]{"Rus Omelette","Chef's special — a crowd favourite","50"}, new String[]{"Chicken Caffreal","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Squid Masala","A timeless classic, done the right way","80"}, new String[]{"Authentic Goan Food","Bursting with authentic flavour","100"}, new String[]{"Pomfret Masala Fry","Customer's most loved dish","60"}, new String[]{"Pomfret Curry","House specialty — highly recommended","70"}));
        saveRestaurant("Turque - Sayaji Hotel","Wakad","Asian, Mughlai, North Indian, Salad","Survey 135/136, Mumbai-Bangalore Bypass Highway, Wakad, Pune","🍚",
            4.7,1360,200,"₹₹",18.59958,73.754765,"Chermoula Chicken, Paneer Tikka Makhani, Matka Murgh, Nargisi Kofta",50,            List.of(new String[]{"Chermoula Chicken","Chef's special — a crowd favourite","50"}, new String[]{"Paneer Tikka Makhani","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Matka Murgh","A timeless classic, done the right way","80"}, new String[]{"Nargisi Kofta","Bursting with authentic flavour","100"}, new String[]{"Dahi Ke Kebab","Customer's most loved dish","60"}, new String[]{"Pineapple Cake","House specialty — highly recommended","70"}));
        saveRestaurant("Cafe Paashh","Kalyani Nagar","Cafe, European, Modern Indian, Desserts, Beverages","Plot E1 & E2, Survey 211/2, Hiremath Park, Near Orange IVY School, Kalyani Nagar, Pune","🎂",
            4.8,554,200,"₹₹",18.544312,73.902211,"Honey Ice Cream, Potato Chat, Golgappa, Soba Noodles",35,            List.of(new String[]{"Honey Ice Cream","Chef's special — a crowd favourite","50"}, new String[]{"Potato Chat","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Golgappa","A timeless classic, done the right way","80"}, new String[]{"Soba Noodles","Bursting with authentic flavour","100"}, new String[]{"Watermelon Cooler","Customer's most loved dish","60"}, new String[]{"Spinach Ravioli","House specialty — highly recommended","70"}));
        saveRestaurant("MOJO Pizza - 2X Toppings","Kothrud","Pizza, Fast Food, Desserts","S- 134, Hissa 3A-2B, CTS 753, Gurukripa, Opposite Lodha Petrol Pump, Kothrud, Pune","🍕",
            4.2,7520,250,"₹₹",18.501992,73.821948,"Cheese Burst, Choco Lava Cake, Pizzas, Paneer Tikka",29,            List.of(new String[]{"Cheese Burst","Chef's special — a crowd favourite","60"}, new String[]{"Choco Lava Cake","Made fresh daily with hand-picked ingredients","80"}, new String[]{"Pizzas","A timeless classic, done the right way","100"}, new String[]{"Paneer Tikka","Bursting with authentic flavour","120"}, new String[]{"Garlic Bread","Customer's most loved dish","70"}, new String[]{"Sauce","House specialty — highly recommended","90"}));
        saveRestaurant("Anna Idli","Baner","South Indian, Beverages","Opposite Aman Honda Showroom, Baner Road, Baner, Pune","🥞",
            4.5,2657,350,"₹₹",18.553295,73.802903,"Bonda Soup, Topi Dosa, Raagi Dosa, Kanchipuram Idli",33,            List.of(new String[]{"Bonda Soup","Chef's special — a crowd favourite","80"}, new String[]{"Topi Dosa","Made fresh daily with hand-picked ingredients","110"}, new String[]{"Raagi Dosa","A timeless classic, done the right way","140"}, new String[]{"Kanchipuram Idli","Bursting with authentic flavour","170"}, new String[]{"Podi Mini Idli","Customer's most loved dish","100"}, new String[]{"Pesarattu Dosa","House specialty — highly recommended","130"}));
        saveRestaurant("The Barkhana","Wakad","Bar Food, Mughlai, Chinese, North Indian, Fast Food, Dessert","Shop 215, 216 & 217, Survey 164, Floor 1, The Address Commercia Building, Near Hinjawadi Flyover, Wa","🍚",
            4.6,1903,200,"₹₹",18.593913,73.756656,"Bang Bang Prawns, Butter Chicken Naanza, Mexican Cheese Fries, Bloody Mary",50,            List.of(new String[]{"Bang Bang Prawns","Chef's special — a crowd favourite","50"}, new String[]{"Butter Chicken Naanza","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Mexican Cheese Fries","A timeless classic, done the right way","80"}, new String[]{"Bloody Mary","Bursting with authentic flavour","100"}, new String[]{"Malai Soya Chaap","Customer's most loved dish","60"}, new String[]{"Cocktail","House specialty — highly recommended","70"}));
        saveRestaurant("Tatva The Vegetarian Kitchen","Wakad","North Indian, Chinese, Continental, South Indian, Fast Food,","Datta Mandir Road, Wakad, Pune","🍔",
            4.4,3390,800,"₹₹₹",18.597092,73.763786,"Rajwadi Paneer, Kesari Paneer Tikka, Paneer Teriyaki, Paneer Koliwada",50,            List.of(new String[]{"Rajwadi Paneer","Chef's special — a crowd favourite","190"}, new String[]{"Kesari Paneer Tikka","Made fresh daily with hand-picked ingredients","260"}, new String[]{"Paneer Teriyaki","A timeless classic, done the right way","320"}, new String[]{"Paneer Koliwada","Bursting with authentic flavour","380"}, new String[]{"Lasooni Paneer","Customer's most loved dish","220"}, new String[]{"Dragon Roll","House specialty — highly recommended","290"}));
        saveRestaurant("Sukanta","Deccan Gymkhana","Gujarati, North Indian, Maharashtrian, Desserts","636, Pulachi Wadi, Deccan Gymkhana, Pune","🎂",
            4.4,3328,700,"₹₹₹",18.517001,73.844287,"Dahi Papadi Chaat, Palak Puri, Sitaphal Rabdi, Amras",20,            List.of(new String[]{"Dahi Papadi Chaat","Chef's special — a crowd favourite","170"}, new String[]{"Palak Puri","Made fresh daily with hand-picked ingredients","220"}, new String[]{"Sitaphal Rabdi","A timeless classic, done the right way","280"}, new String[]{"Amras","Bursting with authentic flavour","340"}, new String[]{"Basket Chat","Customer's most loved dish","200"}, new String[]{"Gujarati Food","House specialty — highly recommended","250"}));
        saveRestaurant("Barometer","Kothrud","Continental, Asian, North Indian, Finger Food","Shop 2, Chintamani Pride, Paschimanagri, City Pride Road, Kothrud, Pune","🥡",
            4.6,1630,200,"₹₹",18.498779,73.81896,"Lebanese Chicken, Basil Pesto Pasta, Sunny Side, Filtered Coffee",31,            List.of(new String[]{"Lebanese Chicken","Chef's special — a crowd favourite","50"}, new String[]{"Basil Pesto Pasta","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Sunny Side","A timeless classic, done the right way","80"}, new String[]{"Filtered Coffee","Bursting with authentic flavour","100"}, new String[]{"Sangria","Customer's most loved dish","60"}, new String[]{"Bacon","House specialty — highly recommended","70"}));
        saveRestaurant("Copa Cabana","Pimple Nilakh","North Indian, Continental, Asian, Italian, Salad, Biryani, S","Aundh Wakad Road, Vishal Nagar, Pimple Nilakh, Pune","🍚",
            4.3,3811,200,"₹₹",18.588542,73.782345,"Veg Aftabi, Paneer Chop Masala, Drunken Chicken, Chicken Shashlik",47,            List.of(new String[]{"Veg Aftabi","Chef's special — a crowd favourite","50"}, new String[]{"Paneer Chop Masala","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Drunken Chicken","A timeless classic, done the right way","80"}, new String[]{"Chicken Shashlik","Bursting with authentic flavour","100"}, new String[]{"Hot Wings","Customer's most loved dish","60"}, new String[]{"Sundae","House specialty — highly recommended","70"}));
        saveRestaurant("Shiv Kailash","Camp Area","Mithai, Ice Cream, Beverages","Shop 5, 14 Cannaught Road, Opposite Pune Station, Camp Area, Pune","☕",
            4.7,690,300,"₹₹",18.527942,73.875601,"Masala Doodh, Masala Milk, Dry Fruit Lassi, Thandai",25,            List.of(new String[]{"Masala Doodh","Chef's special — a crowd favourite","70"}, new String[]{"Masala Milk","Made fresh daily with hand-picked ingredients","100"}, new String[]{"Dry Fruit Lassi","A timeless classic, done the right way","120"}, new String[]{"Thandai","Bursting with authentic flavour","140"}, new String[]{"Falooda","Customer's most loved dish","80"}, new String[]{"Kulfi","House specialty — highly recommended","110"}));
        saveRestaurant("Incognito - Restaurant, Bar & Cafe","Balewadi","Italian, European, North Indian, Asian, Continental, Dessert","F And B 25, Survey 21, Panchshill Business Park, Balewadi, Pune","🍕",
            4.5,2183,200,"₹₹",18.570452,73.774262,"Chocolate Dream, Chicken Cacciatore, Chicken Yakitori, Mushroom Salad",46,            List.of(new String[]{"Chocolate Dream","Chef's special — a crowd favourite","50"}, new String[]{"Chicken Cacciatore","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Chicken Yakitori","A timeless classic, done the right way","80"}, new String[]{"Mushroom Salad","Bursting with authentic flavour","100"}, new String[]{"Nachos N Salsa","Customer's most loved dish","60"}, new String[]{"White Wine","House specialty — highly recommended","70"}));
        saveRestaurant("Marz-O-Rin","MG Road","Fast Food, Desserts, Bakery, Sandwich, Beverages, Shake","6, Bakthiar Plaza,   Camp, MG Road, Pune","🍔",
            4.3,3593,300,"₹₹",18.51644,73.878967,"Chatni Sandwich, Rich Plum Cake, Cheese Spaghetti, Rose Milk",27,            List.of(new String[]{"Chatni Sandwich","Chef's special — a crowd favourite","70"}, new String[]{"Rich Plum Cake","Made fresh daily with hand-picked ingredients","100"}, new String[]{"Cheese Spaghetti","A timeless classic, done the right way","120"}, new String[]{"Rose Milk","Bursting with authentic flavour","140"}, new String[]{"Veg Paneer Roll","Customer's most loved dish","80"}, new String[]{"Chicken Grilled Sandwich","House specialty — highly recommended","110"}));
        saveRestaurant("Jaha's Biryani","Hadapsar","Biryani","Shop Q2, Survey 181, Panchganga Sahakari Society, Near Amanora Mall, Hadapsar, Pune","🍚",
            4.1,6599,200,"₹₹",18.519446,73.937869,"Vegetable Raita, Chocolate, Rice, Chicken",48,            List.of(new String[]{"Vegetable Raita","Chef's special — a crowd favourite","50"}, new String[]{"Chocolate","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Rice","A timeless classic, done the right way","80"}, new String[]{"Chicken","Bursting with authentic flavour","100"}));
        saveRestaurant("Faasos","Salunkhe Vihar Road","Fast Food, North Indian, Wraps, Shake, Desserts","Shop 8, Flat 1, Ground Floor, Survey 18/5/2, CTS 640, Dhanmohini Apartment, Kondhwa, Salunkhe Vihar ","🍔",
            4.1,5408,200,"₹₹",18.478724,73.896466,"Wraps, Rolls, Chicken, Rice",42,            List.of(new String[]{"Wraps","Chef's special — a crowd favourite","50"}, new String[]{"Rolls","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Chicken","A timeless classic, done the right way","80"}, new String[]{"Rice","Bursting with authentic flavour","100"}));
        saveRestaurant("The Chinese Factory","Pimple Saudagar","Chinese","Swami Samarth Colony, Sinhasan Bungalow, Rahatni Phata, Pimple Saudagar, Pune","🥡",
            4.1,6976,200,"₹₹",18.606853,73.780838,"Chili Chicken, Paneer Chilly, Schezwan Fried Rice, Chicken Noodles",50,            List.of(new String[]{"Chili Chicken","Chef's special — a crowd favourite","50"}, new String[]{"Paneer Chilly","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Schezwan Fried Rice","A timeless classic, done the right way","80"}, new String[]{"Chicken Noodles","Bursting with authentic flavour","100"}, new String[]{"Manchow Soup","Customer's most loved dish","60"}, new String[]{"Schezwan Noodles","House specialty — highly recommended","70"}));
        saveRestaurant("Eatsome","Pimple Saudagar","Wraps, Biryani, Kebab, North Indian","Near Shivar Garden, Pimple Saudagar, Pune","🍚",
            4.1,13431,200,"₹₹",18.595341,73.787309,"Wraps, Mushrooms, Paneer Tikka, Biryani",48,            List.of(new String[]{"Wraps","Chef's special — a crowd favourite","50"}, new String[]{"Mushrooms","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Paneer Tikka","A timeless classic, done the right way","80"}, new String[]{"Biryani","Bursting with authentic flavour","100"}));
        saveRestaurant("Yana Sizzlers & Wok","FC Road","Chinese, Seafood, Jamaican, BBQ, Beverages","F P 518, Survey 1142, Unit 2, Elite Colossal, Opposite Police Ground, FC Road, Pune","🥡",
            4.4,2546,200,"₹₹",18.530264,73.843878,"Chicken Salami Sizzler, Caramel Pudding, Chicken Shashlik, Peri Peri Sauce",18,            List.of(new String[]{"Chicken Salami Sizzler","Chef's special — a crowd favourite","50"}, new String[]{"Caramel Pudding","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Chicken Shashlik","A timeless classic, done the right way","80"}, new String[]{"Peri Peri Sauce","Bursting with authentic flavour","100"}, new String[]{"Sizzling Brownie","Customer's most loved dish","60"}, new String[]{"Mashed Potatoes","House specialty — highly recommended","70"}));
        saveRestaurant("Kimchi","Kharadi","Chinese, Asian, Momos, Beverages","Opposite Hyundai Showroom, Sambhaji Nagar, Kharadi, Pune","🥡",
            4.4,2417,800,"₹₹₹",18.547094,73.935983,"Chicken Schezwan Dimsum, Kari Kapitan, Mango Delight, Kimchi",48,            List.of(new String[]{"Chicken Schezwan Dimsum","Chef's special — a crowd favourite","190"}, new String[]{"Kari Kapitan","Made fresh daily with hand-picked ingredients","260"}, new String[]{"Mango Delight","A timeless classic, done the right way","320"}, new String[]{"Kimchi","Bursting with authentic flavour","380"}, new String[]{"Dragon Roll","Customer's most loved dish","220"}, new String[]{"Malaysian Noodles","House specialty — highly recommended","290"}));
        saveRestaurant("L'Apicio","Aundh","Cafe, European, Mediterranean, Continental, Desserts","Shop D 8 & 9, Sai Heritage Society, New DP Road, Near Medipoint Hospital, Aundh, Pune","🎂",
            4.6,898,200,"₹₹",18.56544,73.801523,"Mushroom Ragout, Vietnamese Coffee, Peach Tea, Macaroons",36,            List.of(new String[]{"Mushroom Ragout","Chef's special — a crowd favourite","50"}, new String[]{"Vietnamese Coffee","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Peach Tea","A timeless classic, done the right way","80"}, new String[]{"Macaroons","Bursting with authentic flavour","100"}, new String[]{"Chicken Sandwich","Customer's most loved dish","60"}, new String[]{"Pesto Pasta","House specialty — highly recommended","70"}));
        saveRestaurant("Elephant & Co.","Kalyani Nagar","Continental, Modern Indian, Asian, Italian, Finger Food, Bev","18, Survey 213, 214 & 215/2, Yerwada, Kalyani Nagar, Pune","🍕",
            4.5,1580,200,"₹₹",18.54701,73.90072,"Crispy Pita Bread, Mushroom Crepes, Lotus Stem Honey Chilli, Sweet Potato Fries",35,            List.of(new String[]{"Crispy Pita Bread","Chef's special — a crowd favourite","50"}, new String[]{"Mushroom Crepes","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Lotus Stem Honey Chilli","A timeless classic, done the right way","80"}, new String[]{"Sweet Potato Fries","Bursting with authentic flavour","100"}, new String[]{"Farmhouse Pizza","Customer's most loved dish","60"}, new String[]{"Lamb Chops","House specialty — highly recommended","70"}));
        saveRestaurant("FML - Food Music Love","Magarpatta","North Indian, Mughlai, Chinese, Fast Food, Continental, Beve","S35/35a, 2nd Floor, Seasons Mall, Magarpatta, Hadapsar, Magarpatta, Pune","🍚",
            4.3,3043,200,"₹₹",18.519631,73.930288,"Tandoori Fish Tikka, Barbeque Burger, Tangdi Chicken, Farmhouse Pizza",45,            List.of(new String[]{"Tandoori Fish Tikka","Chef's special — a crowd favourite","50"}, new String[]{"Barbeque Burger","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Tangdi Chicken","A timeless classic, done the right way","80"}, new String[]{"Farmhouse Pizza","Bursting with authentic flavour","100"}, new String[]{"Chicken Popcorn","Customer's most loved dish","60"}, new String[]{"Crispy Corn","House specialty — highly recommended","70"}));
        saveRestaurant("Polka Dots","Aundh","Mediterranean, North Indian, Chinese, Beverages, Desserts","Ground Floor, Westend Mall, Aundh, Pune","🎂",
            4.4,2281,200,"₹₹",18.561971,73.807086,"Mozzarella Fingers, Traditional Roast Chicken, Veg Enchiladas, Paprika Chicken",34,            List.of(new String[]{"Mozzarella Fingers","Chef's special — a crowd favourite","50"}, new String[]{"Traditional Roast Chicken","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Veg Enchiladas","A timeless classic, done the right way","80"}, new String[]{"Paprika Chicken","Bursting with authentic flavour","100"}, new String[]{"Buffalo Chicken Wings","Customer's most loved dish","60"}, new String[]{"Veg Augratin","House specialty — highly recommended","70"}));
        saveRestaurant("Chitale Bandhu Mithaiwale","Deccan Gymkhana","Mithai, Ice Cream, Desserts","759/54, Deccan Gymkhana, Pune","🎂",
            4.6,727,300,"₹₹",18.515585,73.841703,"Amba Barfis, Bhakarwadi, Chitale Bandhu, Amrakhand",21,            List.of(new String[]{"Amba Barfis","Chef's special — a crowd favourite","70"}, new String[]{"Bhakarwadi","Made fresh daily with hand-picked ingredients","100"}, new String[]{"Chitale Bandhu","A timeless classic, done the right way","120"}, new String[]{"Amrakhand","Bursting with authentic flavour","140"}, new String[]{"Farsan","Customer's most loved dish","80"}, new String[]{"Sweets","House specialty — highly recommended","110"}));
        saveRestaurant("Godavari Snacks","Magarpatta","South Indian, Shake","Shop 11, Destination Centre, Magarpatta, Pune","🥞",
            4.0,10647,100,"₹",18.509466,73.928019,"Mirchi Bajji, Pesarattu, Vada, Sambhar",45,            List.of(new String[]{"Mirchi Bajji","Chef's special — a crowd favourite","50"}, new String[]{"Pesarattu","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Vada","A timeless classic, done the right way","80"}, new String[]{"Sambhar","Bursting with authentic flavour","100"}, new String[]{"Idli","Customer's most loved dish","60"}, new String[]{"Chutneys","House specialty — highly recommended","70"}));
        saveRestaurant("BOX8 - Desi Meals","Kharadi","North Indian, Biryani, Wraps, Fast Food, Desserts","Shop 1, Ground Floor, SSR Tower, Eon IT Park Road, Kharadi, Pune","🍚",
            4.0,6305,200,"₹₹",18.549095,73.943506,"Choco Lava Cake, Dal Makhni, Chole, Raita",50,            List.of(new String[]{"Choco Lava Cake","Chef's special — a crowd favourite","50"}, new String[]{"Dal Makhni","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Chole","A timeless classic, done the right way","80"}, new String[]{"Raita","Bursting with authentic flavour","100"}, new String[]{"Sandwiches","Customer's most loved dish","60"}, new String[]{"Chicken Tikka","House specialty — highly recommended","70"}));
        saveRestaurant("Behrouz Biryani","Kondhwa","Biryani, Mughlai, Kebab, Desserts","Shop 8, Flat 1, Ground Floor, Survey 18/5/2, CTS 640, Dhanmohini Apartment, Kondhwa, Pune","🍚",
            4.1,3795,350,"₹₹",18.478657,73.896485,"Mint Raita, Falafel, Gulab Jamun, Mutton Biryani",42,            List.of(new String[]{"Mint Raita","Chef's special — a crowd favourite","80"}, new String[]{"Falafel","Made fresh daily with hand-picked ingredients","110"}, new String[]{"Gulab Jamun","A timeless classic, done the right way","140"}, new String[]{"Mutton Biryani","Bursting with authentic flavour","170"}));
        saveRestaurant("Biryani By Kilo","Kharadi","Biryani, Kebab, Mughlai, Hyderabadi","Shop 4, Survey 4/1, Goodwill Icon, Kharadi Bye Pass Road, Kharadi, Pune","🍚",
            4.0,4462,400,"₹₹",18.553849,73.939587,"Chicken Hydrabadi Biryani, Matka Phirni, Paneer Nawabi, Veg Galouti Kebab",50,            List.of(new String[]{"Chicken Hydrabadi Biryani","Chef's special — a crowd favourite","100"}, new String[]{"Matka Phirni","Made fresh daily with hand-picked ingredients","130"}, new String[]{"Paneer Nawabi","A timeless classic, done the right way","160"}, new String[]{"Veg Galouti Kebab","Bursting with authentic flavour","190"}, new String[]{"Chicken Ghee Roast","Customer's most loved dish","110"}, new String[]{"Dum Biryani","House specialty — highly recommended","140"}));
        saveRestaurant("I'm Lion, Strictly Non-Veg","Bavdhan","Mangalorean, Goan, Seafood, Konkan","U10, Navkar Avenue, 1st Floor, Near Axis Bank, NDA Pashan Road, DSK Raanwara Lane, Bavdhan, Pune","🐟",
            4.5,701,800,"₹₹₹",18.520114,73.778091,"Chicken Sagoti, Chocolate Mud Pie, Chicken Cafreal, Neer Dosa",40,            List.of(new String[]{"Chicken Sagoti","Chef's special — a crowd favourite","190"}, new String[]{"Chocolate Mud Pie","Made fresh daily with hand-picked ingredients","260"}, new String[]{"Chicken Cafreal","A timeless classic, done the right way","320"}, new String[]{"Neer Dosa","Bursting with authentic flavour","380"}, new String[]{"Fish Thali","Customer's most loved dish","220"}, new String[]{"Seafood","House specialty — highly recommended","290"}));
        saveRestaurant("BOX8  -  Desi Meals","Hinjawadi","North Indian, Biryani, Wraps, Fast Food, Desserts","Shop 33, Blue Ridge, Rajiv Gandhi IT Park, Hinjewadi Phase 1, Hinjawadi, Pune","🍚",
            4.0,4124,200,"₹₹",18.580523,73.73605,"Gajar Halwa, Chole, Spicy Food, Rolls",50,            List.of(new String[]{"Gajar Halwa","Chef's special — a crowd favourite","50"}, new String[]{"Chole","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Spicy Food","A timeless classic, done the right way","80"}, new String[]{"Rolls","Bursting with authentic flavour","100"}, new String[]{"Butter Chicken","Customer's most loved dish","60"}));
        saveRestaurant("Chulbul Dhaba","Kharadi","North Indian, Chinese","Survey 6/2/23, Haveli, South Main Road, Opposite Zensar IT Park, Kharadi, Pune","🥡",
            4.1,3304,800,"₹₹₹",18.549473,73.942563,"Mushroom Paratha, Veg Kohlapuri, Matka Murgh, Chilli Paneer Dry",50,            List.of(new String[]{"Mushroom Paratha","Chef's special — a crowd favourite","190"}, new String[]{"Veg Kohlapuri","Made fresh daily with hand-picked ingredients","260"}, new String[]{"Matka Murgh","A timeless classic, done the right way","320"}, new String[]{"Chilli Paneer Dry","Bursting with authentic flavour","380"}, new String[]{"Chicken Dilruba","Customer's most loved dish","220"}, new String[]{"Kaju Curry","House specialty — highly recommended","290"}));
        saveRestaurant("Starbucks Coffee","FC Road","Cafe, Beverages, Fast Food, Desserts","Mosaic Ground Floor West, Opposite Fergusson College Gate 2, FC Road, Pune","🍔",
            4.4,806,600,"₹₹₹",18.522496,73.841094,"Java Chip Frappuccino, Caramel Coffee, Caffe Latte, Brewed Coffee",18,            List.of(new String[]{"Java Chip Frappuccino","Chef's special — a crowd favourite","140"}, new String[]{"Caramel Coffee","Made fresh daily with hand-picked ingredients","190"}, new String[]{"Caffe Latte","A timeless classic, done the right way","240"}, new String[]{"Brewed Coffee","Bursting with authentic flavour","290"}, new String[]{"Mocha","Customer's most loved dish","170"}, new String[]{"Coffees","House specialty — highly recommended","220"}));
        saveRestaurant("Origin Bistro","Pashan","Continental, Italian, European, Beverages, Desserts","Shop 2 A, The Capital, Baner-Pashan Link Road, Pashan, Pune","🍕",
            4.4,801,200,"₹₹",18.552001,73.793772,"Mushroom Pepper, Basil Cooler, French Toast, English Breakfast",36,            List.of(new String[]{"Mushroom Pepper","Chef's special — a crowd favourite","50"}, new String[]{"Basil Cooler","Made fresh daily with hand-picked ingredients","60"}, new String[]{"French Toast","A timeless classic, done the right way","80"}, new String[]{"English Breakfast","Bursting with authentic flavour","100"}, new String[]{"Hot Chocolate","Customer's most loved dish","60"}, new String[]{"Pancakes","House specialty — highly recommended","70"}));
        saveRestaurant("Chaitanya Paranthas","FC Road","North Indian, Chinese, Biryani, Fast Food, Desserts, Beverag","Tukaram Paduka Chowk, FC Road, Pune","🍚",
            4.2,2295,400,"₹₹",18.524325,73.841322,"Sumptuous Paratha, Amritsari Parantha, Mushroom Cheese Paratha, Peshawari Paratha",18,            List.of(new String[]{"Sumptuous Paratha","Chef's special — a crowd favourite","100"}, new String[]{"Amritsari Parantha","Made fresh daily with hand-picked ingredients","130"}, new String[]{"Mushroom Cheese Paratha","A timeless classic, done the right way","160"}, new String[]{"Peshawari Paratha","Bursting with authentic flavour","190"}, new String[]{"Aloo Cheese","Customer's most loved dish","110"}, new String[]{"Mango Lassi","House specialty — highly recommended","140"}));
        saveRestaurant("The Chocolate Room","FC Road","Cafe, Desserts, Bakery, Italian","1229, A Narhari, Goodluck Chowk, Near Sagar Arcade, FC Road, Pune","🍕",
            4.3,1479,700,"₹₹₹",18.518512,73.841527,"Ecstasy Sundae, Choco Lava Lava, Cuddle Cup, Chocolate Fudge Sundae",20,            List.of(new String[]{"Ecstasy Sundae","Chef's special — a crowd favourite","170"}, new String[]{"Choco Lava Lava","Made fresh daily with hand-picked ingredients","220"}, new String[]{"Cuddle Cup","A timeless classic, done the right way","280"}, new String[]{"Chocolate Fudge Sundae","Bursting with authentic flavour","340"}, new String[]{"Chocolate Ecstasy","Customer's most loved dish","200"}, new String[]{"Chocolate Avalanche","House specialty — highly recommended","250"}));
        saveRestaurant("Two Sticks","Balewadi","Chinese","Shop 1, Ground Floor, Avenue Daffodils, Sai Chowk, New DP Road, Balewadi, Pune","🥡",
            4.4,674,800,"₹₹₹",18.57308,73.77076,"Basil Dim Sum, Chicken Laksa, Pho, Wonton Soup",47,            List.of(new String[]{"Basil Dim Sum","Chef's special — a crowd favourite","190"}, new String[]{"Chicken Laksa","Made fresh daily with hand-picked ingredients","260"}, new String[]{"Pho","A timeless classic, done the right way","320"}, new String[]{"Wonton Soup","Bursting with authentic flavour","380"}, new String[]{"Chilly Garlic Noodles","Customer's most loved dish","220"}, new String[]{"Dim Sums","House specialty — highly recommended","290"}));
        saveRestaurant("Arabian Bites","Kondhwa","Arabian, Fast Food, Lebanese, Middle Eastern, Beverages","Shop 02, Bulding 69, Opposite Kausar Baugh Masjid, Kondhwa, Pune","🍔",
            4.3,1420,300,"₹₹",18.473662,73.893555,"Basbusa, Hyderabadi Haleem, Chicken Shwarma Roll, Baklava",43,            List.of(new String[]{"Basbusa","Chef's special — a crowd favourite","70"}, new String[]{"Hyderabadi Haleem","Made fresh daily with hand-picked ingredients","100"}, new String[]{"Chicken Shwarma Roll","A timeless classic, done the right way","120"}, new String[]{"Baklava","Bursting with authentic flavour","140"}, new String[]{"Roll","Customer's most loved dish","80"}, new String[]{"Chicken Biryani","House specialty — highly recommended","110"}));
        saveRestaurant("Peter's Momo Center","Bavdhan","Momos","31, Sagar Co-Operative Housing Society, Pashan Road, Bavdhan, Pune","🍽️",
            4.3,891,100,"₹",18.51509,73.781944,"Fried Momo, Veg Momo, Chicken Momo, Soup",39,            List.of(new String[]{"Fried Momo","Chef's special — a crowd favourite","50"}, new String[]{"Veg Momo","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Chicken Momo","A timeless classic, done the right way","80"}, new String[]{"Soup","Bursting with authentic flavour","100"}, new String[]{"Chutney","Customer's most loved dish","60"}));
        saveRestaurant("Satguru's Punjabi Rasoi","Hinjawadi","North Indian, Chinese, Mughlai","Shop 3, 4, 5, Phase 2 Road, Rajiv Gandhi IT Park, Mulshi, Near HDFC Bank, Hinjewadi, Pune, Hinjawadi","🍚",
            4.2,1498,200,"₹₹",18.594044,73.729686,"Paneer Punjabi, Cheese Fritters, Mughlai Chicken, Authentic Punjabi Food",50,            List.of(new String[]{"Paneer Punjabi","Chef's special — a crowd favourite","50"}, new String[]{"Cheese Fritters","Made fresh daily with hand-picked ingredients","60"}, new String[]{"Mughlai Chicken","A timeless classic, done the right way","80"}, new String[]{"Authentic Punjabi Food","Bursting with authentic flavour","100"}, new String[]{"Paneer Lababdar","Customer's most loved dish","60"}, new String[]{"Dal Fry","House specialty — highly recommended","70"}));
    }

    private void saveRestaurant(String name, String area, String cuisine, String address,
            String emoji, double rating, int votes, int cost, String priceLabel,
            double lat, double lng, String topDishes, int eta, List<String[]> menuData) {
        Restaurant r = new Restaurant();
        r.setName(name); r.setArea(area); r.setCuisine(cuisine); r.setAddress(address);
        r.setEmoji(emoji); r.setRating(rating); r.setVotes(votes); r.setCostForTwo(cost);
        r.setPriceLabel(priceLabel); r.setLat(lat); r.setLng(lng);
        r.setTopDishes(topDishes); r.setEta(eta);
        restaurantRepo.save(r);

        List<MenuItem> items = new ArrayList<>();
        for (String[] d : menuData) {
            MenuItem m = new MenuItem(r, d[0], d[1], Integer.parseInt(d[2]));
            items.add(m);
        }
        r.setMenuItems(items);
        restaurantRepo.save(r);
    }

    private DeliveryPartner dp(String name, String phone, String vehicle, String vNo,
            String area, String zone, double rating, double exp, String avatar) {
        return new DeliveryPartner(name, phone, vehicle, vNo, area, zone, rating, exp, avatar);
    }
}
